version: 2
whitelist: &whitelist
  paths:
    - .npmignore
    - .git/*
    - coverage/*
    - dist/*
    - node_modules/*
    - controllers/*
    - interfaces/*
    - models/*
    - routes/*
    - middlewares/*
    - utils/*
    - logs/index.ts
    - test/*
    - index.ts
    - cc-test-reporter
    - package.json
    - tsconfig.json
    - tslint.json
defaults: &defaults
  working_directory: ~/mentorXpool
  docker:
    - image: circleci/node:latest
    - image: circleci/mongo:latest
persist: &persist
  root: ~/mentorXpool
  <<: *whitelist
restoreCache: &restoreCache
  keys:
    - mentorXpool-dependency-cache-{{ checksum "package.json" }}
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restoreCache
      - run:
          name: Install packages
          command: if (test ! -d ~/mentorXpool/node_modules); then npm ci; fi
      - run:
          name: Setup Code Climate test-reporter
          command: |
            if (test ! -f ~/mentorXpool/cc-test-reporter); then
              echo "downloading clode climate test reporter";
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/mentorXpool/cc-test-reporter;
              chmod +x ~/mentorXpool/cc-test-reporter;
            fi
      - save_cache:
          key: mentorXpool-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/mentorXpool/node_modules
            - ~/mentorXpool/cc-test-reporter
      - persist_to_workspace:
          <<: *persist
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/mentorXpool
      - run:
          name: Lint TypeScript code
          command: npm run lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/mentorXpool
      - run:
          name: Notify Code Climate Of Incomming Coverage Report
          command: ~/mentorXpool/cc-test-reporter before-build
      - run:
          name: Run Tests
          command: npm run test:coverage
      - persist_to_workspace:
          <<: *persist
  coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/mentorXpool
      - run:
          name: Send Coverage To Code Climate
          command: ~/mentorXpool/cc-test-reporter after-build upload-coverage -t lcov
          when: always
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/mentorXpool
      - run:
          name: Build TypeScript Code
          command: npm build
      - persist_to_workspace:
          <<: *persist
  deploy:
    <<: *defaults
    environment:
      PROJECT_NAME: mentorXpool
    steps:
      - attach_workspace:
          at: ~/mentorXpool
      - run:
          name: Build and deploy application
          command: chmod +x .circleci/deploy.sh && .circleci/deploy.sh
workflows:
  version: 2
  setup-lint-test-coverage-build-deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - coverage:
          requires:
            - setup
            - test
      - build:
          requires:
            - lint
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
